name: nylo_support
description: Support library for the Nylo framework. This library supports routing, widgets, localization, cli, storage and more.
version: 6.35.1
homepage: https://nylo.dev
repository: https://github.com/nylo-core/support/tree/6.x
issue_tracker: https://github.com/nylo-core/support/issues
documentation: https://github.com/nylo-core/support
funding:
  - https://github.com/sponsors/agordn52
topics:
  - micro-framework
  - framework

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=3.24.0"

dependencies:
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^6.0.0
  theme_provider: ^0.6.0
  validated: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dio: ^5.9.0
  recase: ^4.1.0
  get_time_ago: ^2.3.2
  flutter_styled_toast: ^2.2.1
  animate_do: ^4.2.0
  pull_to_refresh_flutter3: ^2.0.2
  equatable: ^2.0.7
  rxdart: ^0.28.0
  pretty_dio_logger: ^1.4.0
  intl: ^0.20.2
  skeletonizer: ^2.1.0+1
  error_stack: ^1.10.3
  date_field: ^6.0.3+1
  flutter_multi_formatter: ^2.13.10
  flutter_local_notifications: ^19.4.1
  path_provider: ^2.1.5
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  app_badge_plus: ^1.2.3
  mask_text_input_formatter: ^2.9.0
  uuid: ^4.5.1
  ffi: ^2.1.4
  win32: ^5.14.0
  characters: ^1.4.0
  flutter_web_plugins:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: The Nylo package logo.
    path: screenshots/logo.png

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
