name: Base

on:
  push:
    branches: [main]
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'

  pull_request:
    branches: [main]

  workflow_dispatch:

# This ensures that previous jobs for the PR are canceled when PR is updated
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/minimal-quality.yaml@main
    with:
      codecov-name: form_builder_validators
      enable-generate-l10n: true
  example:
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/build-examples.yaml@main
    with:
      enable-generate-l10n: true


  deployment:
    permissions:
      id-token: write
    uses: flutter-form-builder-ecosystem/.github/.github/workflows/deployment.yaml@main
    with: 
      enable-generate-l10n: true
    if: ${{ github.ref_type == 'tag' }}
    needs: [build, example]
