name: jet
description: "A lightweight, modular Flutter framework for scalable app architecture, providing dependency injection, lifecycle management, and streamlined setup for rapid development. Built with Riverpod 3 for enhanced state management and code generation capabilities."
version: 0.0.3-alpha.2
homepage: https://github.com/fathialamre/jet
repository: https://github.com/fathialamre/jet
issue_tracker: https://github.com/fathialamre/jet/issues

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: "^5.8.0+1"
  hooks_riverpod: "^3.0.0"
  flutter_hooks: "^0.21.2"
  auto_route: "^10.1.0+1"
  flutter_form_builder: "^10.1.0"
  form_builder_validators: "^11.1.2"
  pinput: "^5.0.2"
  custom_refresh_indicator: "^4.0.1"
  infinite_scroll_pagination: "^5.1.0"
  flutter_screenutil: "^5.9.3"
  phosphor_flutter: "^2.1.0"
  guardo: "^0.1.0"
  flutter_secure_storage: "^9.2.4"
  shared_preferences: "^2.5.3"
  intl: "^0.20.2"
  flutter_local_notifications: "^19.4.2"
  timezone: "^0.10.1"
  flutter_timezone: "^4.1.1"
  path_provider: "^2.1.5"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"

flutter:
  generate: true
