name: jet
description: "A comprehensive Flutter framework providing networking, state management, forms, theming, and more."
version: 0.0.1
homepage: https://github.com/your-org/jet
repository: https://github.com/your-org/jet
issue_tracker: https://github.com/your-org/jet/issues

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: "^5.8.0+1"
  hooks_riverpod: "^2.6.1"
  flutter_hooks: "^0.21.2"
  auto_route: "^10.1.0+1"
  flutter_form_builder: "^10.1.0"
  form_builder_validators: "^11.1.2"
  pinput: "^5.0.2"
  custom_refresh_indicator: "^4.0.1"
  infinite_scroll_pagination: "^5.1.0"
  flutter_screenutil: "^5.9.3"
  phosphor_flutter: "^2.1.0"
  guardo: "^0.1.0"
  flutter_secure_storage: "^9.2.4"
  shared_preferences: "^2.5.3"
  intl: "^0.20.2"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"

flutter:
  generate: true
