name: jet
description: "A comprehensive Flutter framework providing networking, state management, forms, theming, and more."
version: 0.0.1
homepage: https://github.com/your-org/jet
repository: https://github.com/your-org/jet
issue_tracker: https://github.com/your-org/jet/issues

environment:
  sdk: ">=3.8.1 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Networking
  dio: "^5.8.0+1"
  
  # State Management
  hooks_riverpod: "^2.6.1"
  flutter_hooks: "^0.21.2"
  
  # Routing
  auto_route: "^10.1.0+1"
  
  # Forms & Validation
  flutter_form_builder: "^10.1.0"
  form_builder_validators: "^11.1.2"
  
  # UI Components
  lucide_icons_flutter: "^3.0.6"
  custom_refresh_indicator: "^4.0.1"
  infinite_scroll_pagination: "^5.1.0"
  flutter_screenutil: "^5.9.3"

  #Utils
  guardo: "^0.1.0"
  
  # Storage
  flutter_secure_storage: "^9.2.4"
  shared_preferences: "^2.5.3"
  
  # Localization
  intl: "^0.20.2"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: "^6.0.0"


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true # Add this line


  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
